config/routes.rb
ProductionRailsV3::Application.routes.draw do
  resources :books do
    resources :pages
    resources :productions, :only => [:index, :new, :create]
    member do
      get :restart_book
    end
  end
  resources :productions do
    member do
      post :confirm
      get :restart
      get :full_restart
    end
  end
  resources :p2flines

  root :to => "main#index"

end

app/views/pages/index.html.haml
%h1 Pages from book #{link_to @book.name, book_path(@book)} (#{@book.id})
%div
 %h3 Productions:
 - @productions.each do |production|
  %div
   #{production.type || 'Production'}: #{production.state}

= will_paginate
%table
 %tr
  %th №
  %th Id
  %th Book
  %th
   %div created
   %div updated
  %th Doc
  %th Text
  %th View
  %th Quote
  %th Abbyy exception
  %th Actions

 - @pages.each do |page|
  %tr{:class=>"#{cycle('even', 'odd')}"}
   %td= link_to page.page_no.to_s, book_page_path(page.book, page)
   %td #{page.id}
   %td= link_to @book.name, book_path(@book)
   %td
    %div #{page.created_at.strftime("%Y-%m-%d %H:%M:%S")}
    %div #{page.updated_at.strftime("%Y-%m-%d %H:%M:%S")}
   %td
    - if page.doc_ready?
     %div #{page.doc_ready_time.andand.strftime("%Y-%m-%d %H:%M:%S") or '---' }
     %div #{page.doc_updated_at.andand.strftime("%Y-%m-%d %H:%M:%S") or '---' }
   %td
    - if page.text_ready?
     %div #{page.text_ready_time.andand.strftime("%Y-%m-%d %H:%M:%S") or '---' }
     %div #{page.text_updated_at.andand.strftime("%Y-%m-%d %H:%M:%S") or '---' }
   %td
    - if page.view_ready?
     %div #{page.view_ready_time.andand.strftime("%Y-%m-%d %H:%M:%S") or '---' }
     %div #{page.view_updated_at.andand.strftime("%Y-%m-%d %H:%M:%S") or '---' }
   %td
    - if page.quote_ready?
     %div #{page.quote_ready_time.andand.strftime("%Y-%m-%d %H:%M:%S") or '---' }
     %div #{page.quote_updated_at.andand.strftime("%Y-%m-%d %H:%M:%S") or '---' }
   %td
    - if page.exception?
     %div #{page.exception_at.andand.strftime("%Y-%m-%d %H:%M:%S") or '---' }
   %td
= will_paginate

app/views/pages/show.html.haml
%div{:align => "center"}
 %h1 Page #{@page.page_no} of #{link_to @page.book.name, book_path(@page.book)}
.links{:align=>"center", :style=>"padding-bottom:20px;"}
 - @links.each do |l|
  %span{:style=>"padding:20px;"}= link_to_unless_current l[0], l[1] if l
- if @page.confirmable?
 - @page.book.productions.with_state(:confirmation_waiting).each do |production|
  %div{:style=>"padding:15px;"}
   = link_to production.type || "Production", production_path(production)
   = button_to "Confirm", confirm_production_path(production), :method => :post
.fast_pages{:align=>"center"}
 - @fast_select_pages.each do |lpage|
  %span{:style=>"padding:10px;"}= link_to_unless_current lpage.page_no.to_s, book_page_path(lpage.book, lpage)

%table
 %tr
  %td
   - if @flash
    .column_flash
     %object{:classid=>"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000", :width=>"700", :height=>"500", :codebase=>"http://active.macromedia.com/flash5/cabs/swflash.cab#version=8,0,0,0"}
      %param{:name=>"MOVIE", :value=>"#{@flash}"}
      %param{:name=>"PLAY", :value=>"true"}
      %param{:name=>"LOOP", :value=>"true"}
      %param{:name=>"QUALITY", :value=>"high"}
      %embed{:src=>"#{@flash}", :width=>"700", :height=>"500", :play=>"true", :align=>"", :loop=>"true", :quality=>"high", :type=>"application/x-shockwave-flash", :pluginspage=>"http://www.macromedia.com/go/getflashplayer"}
  %td
   - if File.exist?("#{@page.full_path}.txt")
    %textarea{:cols=>50, :rows=>30}= File.read("#{@page.full_path}.txt")
   - else
    %div No text file