config/routes.rb
ProductionRailsV3::Application.routes.draw do
  resources :books do
    resources :pages
    resources :productions, :only => [:index, :new, :create]
    member do
      get :restart_book
    end
  end
  resources :productions do
    member do
      post :confirm
      get :restart
      get :full_restart
    end
  end
  resources :p2flines

  root :to => "main#index"

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_format_of :name, :with=>/^(ISBN|DDCC)-[0123456789\-]+[0123456789X]$/uim
  validates_uniqueness_of :name

  has_many :pages
  has_many :productions

  def self.register(book_name)
    #создает или находит книгу и возвращает ее. при ошибках вернуть nil
    book = self.find_or_create_by_name(book_name) #todo params
    book
  end

  def work_catalog
    File.join(WORK_BOOKS_PATH, name)
  end

  def pdf_work_path
    File.join(work_catalog, pdf_filename||"#{name}.pdf")
  end

  def abbyy_input_catalog
    File.join(ABBYY_INPUT_AUTO, name)
  end

  def abbyy_exception_catalog
    File.join(ABBYY_EXCEPTIONS_AUTO, name)
  end

  def abbyy_out_catalog
    File.join(ABBYY_OUTPUT_AUTO, name)
  end

  def get_page_by_file_name(fname)
    nm = fname[4, 4].to_i
    self.pages.find_by_page_no(nm)
  end

  def possible_backup_catalogs
    %w(/mnt/work /mnt/work/2009 /mnt/backup/books) + ["/mnt/backup/books/#{created_at.month.to_s.rjust(2, '0')}"]
  end

  def backup_catalogs
    (possible_backup_catalogs()).map{|p| File.join p, self.name }.select{|p| File.directory? p }
  end

  def restart_book
    self.productions.where(:need_restart => true).each{|p| p.restart_production! }
  end

  #to module backups
  def move_files_to_backup
    update_attributes :locked_at => Time.now
    back_cat = File.join("/mnt/backup/books", created_at.month.to_s.rjust(2, '0'))
    unless File.directory?(back_cat)
      Dir.mkdir(back_cat)
    end
    back_path = File.join(back_cat, name)
    unless File.directory?(back_path)
      FileUtils.rm_f(back_path) if File.exist?(back_path)
      Dir.mkdir(back_path)
    end
    #есть архив, есть пдф, есть сгенеренные пдф/пдц, есть обложки и превью
    flist = []
    flist << "#{name}.pdf" if File.exist?(File.join(work_catalog, "#{name}.pdf"))
    flist << "#{name}.png" if File.exist?(File.join(work_catalog, "#{name}.png"))
    flist << "#{name}.jpg" if File.exist?(File.join(work_catalog, "#{name}.jpg"))
    flist << "#{name}_w.pdf" if File.exist?(File.join(work_catalog, "#{name}_w.pdf"))
    flist << "#{name}.pdc" if File.exist?(File.join(work_catalog, "#{name}.pdc"))
    flist << "#{name}.rar" if File.exist?(File.join(work_catalog, "#{name}.rar"))
    Dir[File.join(work_catalog, "#{name}_test*.jpg")].each{|n| flist << File.basename(n) }
#    flist << "#{name}.pdf" if File.exist?(File.join(work_catalog, "#{name}.pdf"))
    flist.each do |file|
      FileUtils.rm_f File.join(back_path, file)
      FileUtils.cp File.join(work_catalog, file), back_path, :verbose => true
    end
    update_attributes :locked_at => nil, :in_work => false
    FileUtils.rm_r work_catalog
    puts "done #{name}:#{id}"
  end

  def clear_old_backups

  end

  def recover_from_backup

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :get_items, :only => [:index]
  before_filter :get_book, :only => [:show, :restart_book]

  def index
  end

  def show

  end

  def restart_book
    @book.restart_book
    respond_to do |format|
      format.html { redirect_to :back, :notice => "#{@book.name} sent to restart" }
      format.js do
        get_items
        render
      end
    end
  end

  protected
  def get_items
    @books = Book.includes(:productions).paginate(:per_page=>100, :page=>(params.andand[:page] || 1))
    #includes(:productions).
  end

  def get_book
    @book = Book.find(params[:id], :include => [:productions, :pages])
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_row.html.haml
%tr{:class=>cycle('odd', 'even')}
 %td= link_to book_row.id.to_s, book_path(book_row)
 %td= link_to book_row.name, edit_book_path(book_row)
 %td= link_to book_row.productions.count.to_s, book_productions_path(book_row)
 %td
  - book_row.productions.each do |prod|
   %div= link_to (prod.type || 'Production'), production_path(prod)
 %td= link_to (book_row.pages_count || 0).to_s, book_pages_path(book_row)
 %td
  - %w(doc text view quote).each do |str|
   - p = book_row.send("#{str}_pages_count".to_sym) || 0
   %div{:style=>"color:#{ p == book_row.pages_count ? "green" : p > (book_row.pages_count || 0) * 0.75 ? "blue" : :"red" };"}= p
 %td
  - %w(preview).each do |str|
   - p = book_row.send("#{str}_pages_count".to_sym) || 0
   %div{:style=>"color:#{ p == book_row.pages_count ? "green" : p > (book_row.pages_count || 0) * 0.75 ? "blue" : :"red" };"}= p
 %td
  = link_to "restart all", restart_book_book_path(book_row), :remote => true

app/views/books/_books_table.html.haml
%table{:style => "width:100%;"}
 %tr
  %th Id
  %th Name
  %th Tasks count
  %th Tasks
  %th Pages count
  %th! Ready pages<br />doc/text/view/quote
  %th Preview pages
  %th ДД
 = render :partial => "books/book_row", :collection => books

= will_paginate

app/views/books/index.html.haml
#books_table
 = render :partial => "books/books_table", :locals => {:books => @books}

app/views/books/show.html.haml
%h1 Book #{@book.name}
.stats
 %div Pages #{@book.pages_count}
 %div Productions #{@book.productions.count}